# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-21 06:13
from __future__ import unicode_literals

import catan.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(blank=True, choices=[(b'desert', b'desert'), (b'wood', b'wood'), (b'sheep', b'sheep'), (b'stone', b'stone'), (b'brick', b'brick'), (b'wheat', b'wheat')], max_length=20, null=True)),
                ('number', models.PositiveIntegerField()),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[(b'open', b'open'), (b'private', b'private'), (b'playing', b'playing')], default=b'open', max_length=20)),
                ('title', models.CharField(default=catan.models.make_haiku, max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(choices=[(b'settlement', b'settlement'), (b'city', b'city'), (b'road', b'road')], max_length=20)),
                ('loc', models.PositiveIntegerField()),
                ('loc2', models.PositiveIntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(blank=True, choices=[(b'blue', b'blue'), (b'white', b'white'), (b'green', b'green'), (b'red', b'red'), (b'orange', b'orange')], max_length=20, null=True)),
                ('userid', models.IntegerField()),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('vote', models.CharField(blank=True, choices=[(b'default', b'default')], max_length=20, null=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.Lobby')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'desert', b'desert'), (b'wood', b'wood'), (b'sheep', b'sheep'), (b'stone', b'stone'), (b'brick', b'brick'), (b'wheat', b'wheat')], max_length=20)),
                ('path', models.CharField(choices=[(b'catan/img/wheat.png', b'wheat'), (b'catan/img/brick.png', b'brick'), (b'catan/img/stone.png', b'stone'), (b'catan/img/wood.png', b'wood'), (b'catan/img/sheep.png', b'sheep')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[(b'default', b'default')], default=b'default', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='lobby',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catan.Lobby'),
        ),
        migrations.AddField(
            model_name='game',
            name='version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catan.Version'),
        ),
        migrations.AddField(
            model_name='building',
            name='resources',
            field=models.ManyToManyField(to='catan.Resource'),
        ),
        migrations.AddField(
            model_name='building',
            name='version',
            field=models.ManyToManyField(to='catan.Version'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('userid', 'lobby')]),
        ),
        migrations.AlterUniqueTogether(
            name='piece',
            unique_together=set([('game', 'loc', 'loc2')]),
        ),
        migrations.AlterUniqueTogether(
            name='hex',
            unique_together=set([('game', 'row', 'col')]),
        ),
    ]
