# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0002_building_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.Version'),
        ),
    ]
