# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0003_auto_20170222_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='building',
            old_name='version',
            new_name='versions',
        ),
        migrations.RemoveField(
            model_name='building',
            name='resources',
        ),
        migrations.AddField(
            model_name='cost',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.Building'),
        ),
        migrations.AddField(
            model_name='cost',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.Resource'),
        ),
        migrations.AddField(
            model_name='cost',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.Version'),
        ),
    ]
