# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0004_auto_20170222_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='version',
        ),
        migrations.AddField(
            model_name='cost',
            name='version',
            field=models.ManyToManyField(to='catan.Version'),
        ),
    ]
